name: skipthebrowse
description: "SkipTheBrowse - AI-powered movie and TV show recommendation service"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.4

environment:
  sdk: ^3.9.2

dependencies:
  sentry_flutter: ^9.9.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  retrofit: ^4.9.2
  dio: ^5.9.0
  json_annotation: ^4.9.0
  equatable: ^2.0.8
  go_router: ^17.0.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  window_manager: ^0.5.1
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  sentry_dart_plugin: ^3.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  const_date_time: ^1.2.1
  http_mock_adapter: ^0.6.1
  build_runner: ^2.10.2
  retrofit_generator: ^10.2.1
  json_serializable: ^6.11.3
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/providers/

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: skipthebrowse-client
  org: tarbadev

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
  image_path: assets/images/app_icon_1024.png
  adaptive_icon_background: "#000000"